export var firstNames: string[] = [
  "John",
  "Emma",
  "Michael",
  "Sarah",
  "David",

  "Olivia",
  "James",
  "Emily",
  "William",
  "Sophia",

  "Ava",
  "Noah",
  "Isabella",
  "Liam",
  "Charlotte",

  "Ethan",
  "Amelia",
  "Mason",
  "Mia",
  "Benjamin",

  "Mateo",
  "Alejandra",
  "Louis",
  "Camille",
  "Giovanni",

  "Isabella",
  "Lukas",
  "Sophie",
  "Dmitri",
  "Natalia",

  "Hiroshi",
  "Sakura",
  "Wei",
  "Li",
  "Thiago",

  "Gabriela",
  "Lachlan",
  "Matilda",
  "Jane",
  "Toby",
];

export var lastNames: string[] = [
  "Smith",
  "Johnson",
  "Williams",
  "Jones",
  "Brown",

  "Davis",
  "Miller",
  "Wilson",
  "Moore",
  "Taylor",

  "Anderson",
  "Thomas",
  "Jackson",
  "White",
  "Harris",

  "Martin",
  "Thompson",
  "Garcia",
  "Martinez",
  "Robinson",

  "Hernandez",
  "Garcia",
  "Dubois",
  "Leroy",
  "Rossi",

  "Conti",
  "Muller",
  "Schmidt",
  "Ivanov",
  "Petrova",

  "Sato",
  "Tanaka",
  "Wang",
  "Zhang",
  "Silva",

  "Santos",
  "Smith",
  "Wilson",
  "Peterson",
  "York",
];

// data arrays
export const domains = [
  ".com",
  ".net",
  ".org",
  ".co",
  ".io",
  ".info",
  ".biz",
  ".me",
  ".tv",
  ".us",
  ".ca",
  ".uk",
  ".au",
  ".de",
  ".fr",
  ".es",
  ".it",
  ".nl",
  ".jp",
  ".cn",
  ".edu",
  ".gov",
  ".mil",
  ".int",
  ".mobi",
  ".name",
  ".pro",
  ".travel",
  ".aero",
  ".asia",
];

export const nameList = [
  "ba",
  "be",
  "bi",
  "bo",
  "bu",
  "ca",
  "ce",
  "ci",
  "co",
  "cu",
  "da",
  "de",
  "di",
  "do",
  "du",
  "fa",
  "fe",
  "fi",
  "fo",
  "fu",
  "ga",
  "ge",
  "gi",
  "go",
  "gu",
  "ha",
  "he",
  "hi",
  "ho",
  "hu",
  "ja",
  "je",
  "ji",
  "jo",
  "ju",
  "ka",
  "ke",
  "ki",
  "ko",
  "ku",
  "la",
  "le",
  "li",
  "lo",
  "lu",
  "ma",
  "me",
  "mi",
  "mo",
  "mu",
  "na",
  "ne",
  "ni",
  "no",
  "nu",
  "pa",
  "pe",
  "pi",
  "po",
  "pu",
  "ra",
  "re",
  "ri",
  "ro",
  "ru",
  "sa",
  "se",
  "si",
  "so",
  "su",
  "ta",
  "te",
  "ti",
  "to",
  "tu",
  "va",
  "ve",
  "vi",
  "vo",
  "vu",
  "wa",
  "we",
  "wi",
  "wo",
  "wu",
  "ya",
  "ye",
  "yi",
  "yo",
  "yu",
  "za",
  "ze",
  "zi",
  "zo",
  "zu",
  "bla",
  "ble",
  "bli",
  "blo",
  "blu",
  "cla",
  "cle",
  "cli",
  "clo",
  "clu",
  "dla",
  "dle",
  "dli",
  "dlo",
  "dlu",
  "fla",
  "fle",
  "fli",
  "flo",
  "flu",
  "gla",
  "gle",
  "gli",
  "glo",
  "glu",
  "pla",
  "ple",
  "pli",
  "plo",
  "plu",
  "sla",
  "sle",
  "sli",
  "slo",
  "slu",
  "vla",
  "vle",
  "vli",
  "vlo",
  "vlu",
  "bra",
  "bre",
  "bri",
  "bro",
  "bru",
  "cra",
  "cre",
  "cri",
  "cro",
  "cru",
  "dra",
  "dre",
  "dri",
  "dro",
  "dru",
  "fra",
  "fre",
  "fri",
  "fro",
  "fru",
  "gra",
  "gre",
  "gri",
  "gro",
  "gru",
  "pra",
  "pre",
  "pri",
  "pro",
  "pru",
  "sra",
  "sre",
  "sri",
  "sro",
  "sru",
  "vra",
  "vre",
  "vri",
  "vro",
  "vru",
  "bla",
  "ble",
  "bli",
  "blo",
  "blu",
  "cla",
  "cle",
  "cli",
  "clo",
  "clu",
  "dla",
  "dle",
  "dli",
  "dlo",
  "dlu",
  "fla",
  "fle",
  "fli",
  "flo",
  "flu",
  "gla",
  "gle",
  "gli",
  "glo",
  "glu",
  "pla",
  "ple",
  "pli",
  "plo",
  "plu",
  "sla",
  "sle",
  "sli",
  "slo",
  "slu",
  "vla",
  "vle",
  "vli",
  "vlo",
  "vlu",
  "bra",
  "bre",
  "bri",
  "bro",
  "bru",
  "cra",
  "cre",
  "cri",
  "cro",
  "cru",
  "dra",
  "dre",
  "dri",
  "dro",
  "dru",
  "fra",
  "fre",
  "fri",
  "fro",
  "fru",
  "gra",
  "gre",
  "gri",
  "gro",
  "gru",
  "pra",
  "pre",
  "pri",
  "pro",
  "pru",
  "sra",
  "sre",
  "sri",
  "sro",
  "sru",
  "vra",
  "vre",
  "vri",
  "vro",
  "vru",
  "brah",
  "breh",
  "brih",
  "broh",
  "bruh",
  "crah",
  "creh",
  "crih",
  "croh",
  "cruh",
  "drah",
  "dreh",
  "drih",
  "droh",
  "druh",
  "frah",
  "freh",
  "frih",
  "froh",
  "fruh",
  "grah",
  "greh",
  "grih",
  "groh",
  "gruh",
  "prah",
  "preh",
  "prih",
  "proh",
  "pruh",
  "srah",
  "sreh",
  "srih",
  "sroh",
  "sruh",
  "vrah",
  "vreh",
  "vrih",
  "vroh",
  "vruh",
];

export var videoInfos = [
  { url: "9jf3X9Yz0mY", title: "Love Song", description: "Romantic ballad" },
  {
    url: "3L4YrGaR8E4",
    title: "Bulls On Parade",
    description: "Energetic rock anthem",
  },
  { url: "ErvgV4P6Fzc", title: "Patience", description: "Soft rock classic" },
  {
    url: "kijpcUv-b8M",
    title: "Somebody To Love",
    description: "Iconic Queen hit",
  },
  {
    url: "Lo2qQmj0_h4",
    title: "You Shook Me All Night Long",
    description: "Hard rock anthem",
  },

  {
    url: "TLV4_xaYynY",
    title: "All Along The Watchtower",
    description: "Bob Dylan classic",
  },
  {
    url: "usNsCeOV4GM",
    title: "A Day In The Life",
    description: "Beatles masterpiece",
  },
  {
    url: "6ul-cZyuYq4",
    title: "Go Your Own Way",
    description: "Fleetwood Mac classic",
  },
  {
    url: "x7bIbVlIqEc",
    title: "Nothing else matter",
    description: "Metallica's iconic ballad",
  },
  {
    url: "G3LvhdFEOqs",
    title: "Mr. Crowley",
    description: "Ozzy Osbourne classic",
  },

  {
    url: "VYOjWnS4cMY",
    title: "This Is America",
    description: "Donald Glover's social commentary",
  },
  {
    url: "nOvKal4nhU0",
    title: "It's A Man's Man's Man's World",
    description: "James Brown's soulful anthem",
  },
  {
    url: "OINw340XQbg",
    title: "Stand by Me",
    description: "Ben E. King's timeless classic",
  },
  {
    url: "GZ3zL7kT6_c",
    title: "Lose Control",
    description: "Energetic dance track",
  },
  {
    url: "bpOSxM0rNPM",
    title: "Do I Wanna Know?",
    description: "Arctic Monkeys' moody indie rock",
  },

  {
    url: "TJAfLE39ZZ8",
    title: "Back To Black",
    description: "Amy Winehouse's soulful lament",
  },
  {
    url: "Edwsf-8F3sI",
    title: "Feeling Good",
    description: "Nina Simone's uplifting anthem",
  },
  {
    url: "4sfhvxTZ0wo",
    title: "Fifteen Feet Of Pure White Snow",
    description: "Nick Cave's haunting ballad",
  },
  {
    url: "u91flodrsnI",
    title: "I've Been Loving You Too Long",
    description: "Otis Redding's soulful ballad",
  },
  {
    url: "NlwIDxCjL-8",
    title: "Shape of My Heart",
    description: "Sting's introspective classic",
  },

  {
    url: "oNPFbz4c3v4",
    title: "When A Man Loves A Woman/It's A Mans World",
    description: "Soulful classic",
  },
  {
    url: "ShiShrR_nh8",
    title: "Anthem for the Year 2000",
    description: "Rock anthem",
  },
  {
    url: "lS03VudGTKE",
    title: "Linkin Park Feat. Chris Cornell Crawling",
    description: "Powerful collaboration",
  },
  { url: "JquzYr-5bE4", title: "Nature Boy", description: "Jazz standard" },
  {
    url: "QzmMB8dTwGs",
    title: "Henry Lee ft. P.J Harvey",
    description: "Dark and haunting duet",
  },

  {
    url: "vVXIK1xCRpY",
    title: "Show Me How to Live",
    description: "Rock anthem",
  },
  { url: "Dn8vzTsnPps", title: "My Way", description: "Frank Sinatra classic" },
  {
    url: "EDKwCvD56kw",
    title: "Youth of the Nation",
    description: "Nu metal anthem",
  },
  {
    url: "JTMVOzPPtiw",
    title: "Nookie",
    description: "Limp Bizkit's rap metal anthem",
  },
  {
    url: "8-r-V0uK4u0",
    title: "Bullet With Butterfly Wings",
    description: "Smashing Pumpkins' alt-rock anthem",
  },

  {
    url: "eBG7P-K-r1Y",
    title: "Everlong",
    description: "Foo Fighters' alternative rock anthem",
  },
  {
    url: "-JJAXwAaA2w",
    title: "The Bitter End",
    description: "Placebo's alt-rock anthem",
  },
  {
    url: "s88r_q7oufE",
    title: "No One Knows",
    description: "Queens of the Stone Age's alt-rock anthem",
  },
  {
    url: "hbe3CQamF8k",
    title: "Angel",
    description: "Sarah McLachlan's emotional ballad",
  },
  {
    url: "TqhOVY58zIo",
    title: "The Weeping Song",
    description: "Nick Cave's haunting ballad",
  },

  {
    url: "n6P0SitRwy8",
    title: "Heart-Shaped Box",
    description: "Nirvana's grunge anthem",
  },
  {
    url: "3mbBbFH9fAg",
    title: "Black Hole Sun",
    description: "Soundgarden's grunge anthem",
  },
  {
    url: "AEB6ibtdPZc",
    title: "Hard Times",
    description: "Paramore's anthemic rock track",
  },
  {
    url: "auzfTPp4moA",
    title: "Heads Will Roll",
    description: "Yeah Yeah Yeahs' indie rock anthem",
  },
  {
    url: "8iJMOBcPQyg",
    title: "Frijolero",
    description: "Molotov's politically charged rock anthem",
  },

  {
    url: "rtL5oMyBHPs",
    title: "Little Dark Age",
    description: "MGMT's synth-pop masterpiece",
  },
  {
    url: "mpaPBCBjSVc",
    title: "Tighten Up",
    description: "The Black Keys' bluesy rock anthem",
  },
  {
    url: "FiUNDeuBbi8",
    title: "Gouge Away",
    description: "Pixies' alternative rock anthem",
  },
  {
    url: "NzPtr_n-m8A",
    title: "Paranoid Android",
    description: "Radiohead's experimental epic",
  },
  {
    url: "ijxk-fgcg7c",
    title: "Lullaby",
    description: "The Cure's haunting lullaby",
  },

  {
    url: "LY42nUEHQMk",
    title: "Jigsaw Falling into",
    description: "Radiohead's enigmatic track",
  },
  {
    url: "GhCXAiNz9Jo",
    title: "Take Me Out",
    description: "Franz Ferdinand's indie rock anthem",
  },
  {
    url: "Uz1Jwyxd4tE",
    title: "Hate to Say I Told You So",
    description: "The Hives' garage rock anthem",
  },
  {
    url: "K4dx42YzQCE",
    title: "The Hardest Button To Button",
    description: "The White Stripes' garage rock anthem",
  },
  {
    url: "z5rRZdiu1UE",
    title: "Sabotage",
    description: "Beastie Boys' high-energy track",
  },

  {
    url: "674KGKRQBPE",
    title: "Love Will Tear Us Apart",
    description: "Joy Division's post-punk anthem",
  },
  {
    url: "ZWmrfgj0MZI",
    title: "Unfinished Sympathy",
    description: "Massive Attack's iconic trip-hop track",
  },
  {
    url: "4D2qcbu26gs",
    title: "I Wanna Be Adored",
    description: "The Stone Roses' alternative rock anthem",
  },
  {
    url: "3wk7C64kaP4",
    title: "Zero",
    description: "The Smashing Pumpkins' alt-rock anthem",
  },
  {
    url: "2w6kHS_IRrE",
    title: "2 + 2 = 5",
    description: "Radiohead's experimental rock track",
  },

  {
    url: "Ek0SgwWmF9w",
    title: "Muse - Madness",
    description: "Muse's alternative rock anthem",
  },
  {
    url: "E-OY8K3cEmI",
    title: "Rinzler",
    description: "Placebo's alt-rock anthem",
  },
  {
    url: "PbgKEjNBHqM",
    title: "In Bloom",
    description: "Nirvana's grunge anthem",
  },
  {
    url: "f-H9bbi0Vyw",
    title: "Black Sheep",
    description: "Metric's indie rock anthem",
  },
  {
    url: "XFkzRNyygfk",
    title: "Creep",
    description: "Radiohead's iconic alt-rock anthem",
  },

  {
    url: "V5UOC0C0x8Q",
    title: "Plush",
    description: "Stone Temple Pilots' grunge anthem",
  },
  {
    url: "OMaycNcPsHI",
    title: "Every You Every Me",
    description: "Placebo's alt-rock anthem",
  },
  {
    url: "fgT9zGkiLig",
    title: "Drive",
    description: "Incubus' alternative rock anthem",
  },
  {
    url: "G_sBOsh-vyI",
    title: "Knights Of Cydonia",
    description: "Muse's epic space rock anthem",
  },
  {
    url: "8UVNT4wvIGY",
    title: "Somebody That I Used To Know",
    description: "Melancholic indie-pop masterpiece",
  },

  {
    url: "HyHNuVaZJ-k",
    title: "Feel Good Inc.",
    description: "Eclectic animated music adventure",
  },
  {
    url: "jhsyc81VcB4",
    title: "Knives Out",
    description: "Surrealistic, mysterious visual journey",
  },
  {
    url: "Nco_kh8xJDs",
    title: "Would?",
    description: "Raw, introspective grunge anthem",
  },
  {
    url: "fregObNcHC8",
    title: "The Man Who Sold The World",
    description: "Legendary Bowie's existential masterpiece",
  },
  {
    url: "WAXnqjUfal4",
    title: "Beetlebum",
    description: "Blur's psychedelic rock trip",
  },

  {
    url: "1V_xRb0x9aw",
    title: "Clint Eastwood",
    description: "Gorillaz's genre-blending hip-hop debut",
  },
  {
    url: "pkcJEvMcnEg",
    title: "Lithium",
    description: "Nirvana's iconic grunge anthem",
  },
  {
    url: "wDjeBNv6ip0",
    title: "Lost On You",
    description: "Soulful indie ballad journey",
  },
  {
    url: "MUaL1FnotRQ",
    title: "Bombtrack",
    description: "Rage Against the Machine's explosive anthem",
  },
  {
    url: "w8KQmps-Sog",
    title: "Uprising",
    description: "Muse's anthemic call-to-action",
  },

  {
    url: "GLvohMXgcBo",
    title: "Under The Bridge",
    description: "Red Hot Chili Peppers' timeless classic",
  },
  {
    url: "q-KE9lvU810",
    title: "Cherub Rock",
    description: "Smashing Pumpkins' alternative rock gem",
  },
  {
    url: "LCJblaUkkfc",
    title: "Street Spirit (Fade Out)",
    description: "Radiohead's hauntingly beautiful masterpiece",
  },
  {
    url: "pFptt7Cargc",
    title: "Let It Happen",
    description: "Tame Impala's psychedelic sonic journey",
  },
  {
    url: "OKNQRbJeGNY",
    title: "where is my mind?",
    description: "Pixies' iconic indie rock track",
  },
];

export var videoComments = [
  "Iconic rock anthem, energetic performance",
  "Soulful ballad, emotional lyrics",
  "Indie rock anthem, catchy melody",
  "Classic jazz standard, timeless performance",
  "Alternative rock anthem, powerful vocals",
  "Energetic pop hit, infectious rhythm",
  "Soothing acoustic ballad, heartfelt lyrics",
  "Epic orchestral masterpiece, cinematic experience",
  "Experimental electronic track, hypnotic beats",
  "Sensual R&B groove, sultry vocals",
  "Funky disco anthem, groovy bassline",
  "Spirited folk ballad, storytelling lyrics",
  "Electrifying dance track, pulsating energy",
  "Soulful gospel performance, uplifting message",
  "Dreamy shoegaze anthem, ethereal atmosphere",
  "Reggae-infused pop hit, infectious groove",
  "Hip-hop classic, iconic beats",
  "Powerful rock ballad, anthemic chorus",
  "Soothing ambient track, atmospheric soundscape",
  "Energetic punk anthem, rebellious spirit",
  "Melancholic indie ballad, introspective lyrics",
  "Fierce metal track, blistering guitar solos",
  "Sensual Latin groove, passionate vocals",
  "Electro-pop anthem, infectious hooks",
  "Melodic trance track, euphoric vibes",
  "Soul-stirring blues performance, gritty vocals",
  "Ethereal folk ballad, haunting melody",
  "Upbeat ska anthem, infectious horn section",
  "Dark synth-pop track, moody atmosphere",
  "Spirited country ballad, heartfelt storytelling",
  "Futuristic EDM track, pulsating beats",
  "Soulful reggae ballad, laid-back vibe",
  "Catchy pop-rock anthem, sing-along chorus",
  "Hypnotic trip-hop track, atmospheric beats",
  "Intense metalcore anthem, aggressive vocals",
  "Funky jazz fusion, virtuosic instrumentation",
  "Sultry neo-soul groove, smooth vocals",
  "Epic orchestral rock anthem, cinematic buildup",
  "Spirited indie pop track, infectious energy",
  "Folk-rock anthem, uplifting harmonies",
  "Sensual R&B ballad, intimate lyrics",
  "Energetic ska-punk anthem, infectious energy",
  "Gritty garage rock track, raw vocals",
  "Dreamy synthwave anthem, nostalgic vibes",
  "Melancholic indie folk ballad, emotive storytelling",
  "Soulful blues performance, emotive guitar solos",
  "Epic progressive rock track, virtuosic instrumentation",
  "Spirited pop-punk anthem, catchy hooks",
  "Sensual bossa nova groove, smooth vocals",
  "Energetic electronic dance track, pulsating beats",
  "Haunting gothic rock anthem, atmospheric guitars",
  "Funky disco-pop hit, infectious rhythm",
  "Soothing acoustic folk ballad, heartfelt lyrics",
  "Epic orchestral soundtrack, cinematic adventure",
  "Intense metal anthem, blistering guitar riffs",
  "Soul-stirring gospel performance, uplifting message",
  "Energetic synth-pop anthem, infectious hooks",
  "Sensual R&B groove, sultry vocals",
  "Dreamy indie rock ballad, ethereal atmosphere",
  "Funky jazz fusion, virtuosic improvisation",
  "Melancholic indie pop anthem, introspective lyrics",
  "Spirited country-rock track, anthemic chorus",
  "Epic orchestral metal anthem, cinematic climax",
  "Sultry neo-soul ballad, smooth vocals",
  "Energetic punk-pop anthem, catchy melodies",
  "Gritty blues-rock track, emotive vocals",
  "Dreamy shoegaze anthem, ethereal guitars",
  "Melodic metalcore anthem, soaring vocals",
  "Spirited folk-rock ballad, anthemic chorus",
  "Soulful reggae groove, laid-back vibe",
  "Energetic indie pop track, infectious energy",
  "Funky disco anthem, groovy bassline",
  "Sensual R&B ballad, intimate lyrics",
  "Dreamy synth-pop track, nostalgic vibes",
  "Spirited ska-punk anthem, infectious energy",
  "Sultry jazz standard, smooth vocals",
  "Epic orchestral rock anthem, cinematic grandeur",
  "Melancholic indie folk ballad, emotive storytelling",
  "Soul-stirring blues performance, gritty vocals",
  "Energetic electronic dance track, pulsating beats",
  "Haunting gothic rock anthem, atmospheric guitars",
  "Soothing acoustic folk ballad, heartfelt lyrics",
  "Intense metalcore anthem, aggressive vocals",
  "Epic progressive rock track, virtuosic instrumentation",
  "Spirited pop-punk anthem, catchy hooks",
  "Sensual bossa nova groove, smooth vocals",
  "Funky disco-pop hit, infectious rhythm",
  "Soulful R&B ballad, emotive vocals",
  "Dreamy indie rock anthem, ethereal atmosphere",
];

export const usageText = `Usage: bun seed.ts <number-of-users>

Error: Please provide the correct number of users to generate the seed data.

<number-of-users> must be a positive integer between 1 and ${firstNames.length}, inclusive.

Example: bun seed.ts 11`;
